### ISSUE TITLE
Link to the demo files in tutorials is broken

### ISSUE THREAD

**Issue by basilrabi** [opengeostat/pygslib#10]
I tried downloading the [demo files](https://opengeostat.github.io/pygslib/_files/PyGSLIB_Tutorial1.zip) but the link seems to be broken.

Thank you for the great work.

**Comment by opengeostat** [comment]
Hi basilrabi, 

thank you for using PyGSLIB. 

The plan is updating the demo and creating a new separated repo. There are changes in the new code non compatibles with the code in this old demo.

**Comment by opengeostat** [comment]
Hi basilrabi,

The files requested and updated to the new development source code are in `pygslib/pygslib/Ipython_templates/Tutorial_1`

This is optimized for python 2.7 and 3.6.
