### ISSUE TITLE
Problem with vktools

### ISSUE THREAD

**Issue by mlaloux** [opengeostat/pygslib#2]
When I try

`renderer = gslib.vtktools.polydata2renderer(mycube, color=(1,0,0), opacity=0.50, background=(1,1,1))`

The result is 

```
cython_code/vtktools.pyx in pygslib.vtktools.polydata2renderer (cython_code/vtktools.c:3902)()
cython_code/vtktools.pyx in pygslib.vtktools.polydata2renderer (cython_code/vtktools.c:3471)()
AttributeError: SetInputData
```
(Mac OS X, Python 2.7.12, compiled by me)

**Comment by opengeostat** [comment]
The rendering functions were removed. You may export VTK objects and visualize it in an external viewer, e.g. Paraview.
