### ISSUE TITLE
I cannot install pygslib in Anaconda

### ISSUE THREAD

**Issue by hubzhu** [opengeostat/pygslib#27]
This is the error message I got when trying to run conda and install pygslib.  Same issue on Linux.

conda install -c opengeostat pygslib
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pygslib
  - ezdxf

Current channels:

  - https://conda.anaconda.org/opengeostat/osx-64
  - https://conda.anaconda.org/opengeostat/noarch
  - https://conda.anaconda.org/anaconda-fusion/osx-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by opengeostat** [comment]
hubzhu, 

This is because ezdxf is in conda-forge. Please try `conda install pygslib -c opengeostat -c conda-forge`. You may find more information about installing pygslib at https://github.com/opengeostat/pygslib/wiki/Installing-pygslib-with-conda

**Comment by hubzhu** [comment]
I ran "conda install -c anaconda libgfortran" to install libgfortran.  
After installation I can see the libgfortran.3.dylib file under "anaconda3/pkgs/libgfortran-3.0.1-h93005f0_2/lib/".   

However, when I import pygslib in Jupyter Notebook, it still looked for libgfortran in /usr/local/gfotran and return the same error message in my last thread.

**Comment by emreekm** [comment]
I have the same errors

What's the solution?

**Comment by tunanottechnical** [comment]
is there a solution for this?

**Comment by joooseb** [comment]
I can't install package too

**Comment by raonisalomao** [comment]
Same error here. Any solution since?

**Comment by joooseb** [comment]
> Same error here. Any solution since?

What operation system are you using for?

**Comment by markjuvert** [comment]
Hey guys, anyone got a fix on pygslib?
I tried using python 2.7, 3.6 and 3.7 but each and everyone got it's own error. 

With python 2.7 It does work but when i try to this command 
mydholedb = pygslib.drillhole.Drillhole(collar=collar, survey=survey), 
it gives me AttributeError: module 'pygslib' has no attribute 'drillhole'.

With python 3.6 it's the image error: opt/anaconda3/lib/python3.6/site-packages/pygslib/gslib/__gslib__kt3d.cpython-36m-darwin.so 
 Reason: image not found

And with 3.7, i managed to install pygslib from source code but then I end up with AttributeError: module 'pygslib' has no attribute 'drillhole'.

I've been trying to fix this for days now. 

Please let me know if there's a way around this. 

Thanks in Advanced.

**Comment by 10041964** [comment]
> mydholedb = pygslib.drillhole.Drillhole(collar=collar, survey=survey),

did you get a reply to this error

**Comment by MBourges5** [comment]
Hi, 

I would like to use pygslib. I have installed it. 
In a Jupyter notebook, when I run the command: import pygslib, I get the following error message:

"---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_2020\3607251781.py in <module>
----> 1 import pygslib

~\Anaconda3\lib\site-packages\pygslib\__init__.py in <module>
     24 
     25 # import pygslib modules (compatible with python 3x)
---> 26 from pygslib import drillhole, blockmodel, vtktools, nonlinear, sandbox, gslib, plothtml, charttable, progress, surpac
     27 
     28 from pygslib import version

cython_code\drillhole.pyx in init pygslib.drillhole()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
"
Any ideas?
