### ISSUE TITLE
ERROR collecting tests/test_drillhole_ang2cart_t01.py

### ISSUE THREAD

**Issue by heberallin** [opengeostat/pygslib#28]
hello everyone mi name is Heber from Chile and I appreciate very much the work developed with this python library,  but I have the following problem when I install pygslib:

`=================================== ERRORS ====================================
____________ ERROR collecting tests/test_drillhole_ang2cart_t01.py ____________
tests\test_drillhole_ang2cart_t01.py:3: in <module>
    from pygslib.drillhole import ang2cart
E   ModuleNotFoundError: No module named 'pygslib'
____________ ERROR collecting tests/test_drillhole_ang2cart_t01.py ____________
ImportError while importing test module 'C:\Users\Heber\Desktop\python_heber\pygslib\tests\test_drillhole_ang2cart_t01.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_drillhole_ang2cart_t01.py:3: in <module>
    from pygslib.drillhole import ang2cart
E   ModuleNotFoundError: No module named 'pygslib'
____________ ERROR collecting tests/test_drillhole_ang2cart_t02.py ____________
tests\test_drillhole_ang2cart_t02.py:4: in <module>
    from pygslib.drillhole import ang2cart
E   ModuleNotFoundError: No module named 'pygslib'
____________ ERROR collecting tests/test_drillhole_ang2cart_t02.py ____________
ImportError while importing test module 'C:\Users\Heber\Desktop\python_heber\pygslib\tests\test_drillhole_ang2cart_t02.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_drillhole_ang2cart_t02.py:4: in <module>
    from pygslib.drillhole import ang2cart
E   ModuleNotFoundError: No module named 'pygslib'
!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 4 error in 0.37 seconds ===========================
 OPENGEOSTAT SAYS CYTHON/FORTRAN CODE COMPILED`

I use Python 3.6.4.

Thank you in advance for your help.

**Comment by opengeostat** [comment]
Hi heberallin, 

Please use `python setup.py build` and  `python setup.py install`.  This error is on testing, not at complying. You will need to install pygslib using `python setup.py install` to make the tests work.
