### ISSUE TITLE
BABBITT zone data

### ISSUE THREAD

**Issue by variog** [opengeostat/pygslib#35]
Greetings,
I am a graduate student in Geology and my thesis is reserve estimation. For this purpose, I want to get help from PyGSLIB library. Ihave used https://opengeostat.github.io/pygslib/Tutorial.html to learn, but i can not download  BABBITT zone of the KEWEENAWAN DULUTH COMPLEX data. please send me this data for better learning. Thanks for your gratitude.

**Comment by nshea3** [comment]
You should be able to find the demo files in `pygslib/pygslib/Ipython_templates/Tutorial_1`.

**Comment by variog** [comment]
I realized, thanks a lot.

    On Friday, June 21, 2019, 11:56:01 PM GMT+4:30, Nicholas Shea <notifications@github.com> wrote:  
 
 
You should be able to find the demo files in pygslib/pygslib/Ipython_templates/Tutorial_1.

**Comment by variog** [comment]
Hello,
I also can not download  the demo files. Failed during the download, I think it's reason is downloading from Iran and Iran is being sanctioned. In demonstration video exists a domain file but not in pygslib/Ipython_templates/Tutorial_1/Babbitt . When I replace my data, I have a lot of errors.

   On Saturday, June 22, 2019, 03:27:35 PM GMT+4:30, vario gram <varo_gram@yahoo.com> wrote:  
 
  I realized, thanks a lot.

    On Friday, June 21, 2019, 11:56:01 PM GMT+4:30, Nicholas Shea <notifications@github.com> wrote:  
 
 
You should be able to find the demo files in pygslib/pygslib/Ipython_templates/Tutorial_1.

**Comment by nshea3** [comment]
What errors do you see?

When you say the download fails, are you cloning the repository or downloading the files directly?

**Comment by variog** [comment]
I do not have 'domain.stl' file of BABBITT zone that needs to be blocked. If you can send this file to me. 
    On Saturday, June 29, 2019, 10:02:51 AM GMT+4:30, Nicholas Shea <notifications@github.com> wrote:  
 
 
What errors do you see?

When you say the download fails, are you cloning the repository or downloading the files directly?

**Comment by nshea3** [comment]
Archived directory is attached, let me know if you are able to download and open it

[Babbitt.zip](https://github.com/opengeostat/pygslib/files/3357790/Babbitt.zip)

**Comment by variog** [comment]
I have two problems:1. I can not download the domain.stl file. I already downloaded the files you sent, but there is no domain.stl file.2. For the Variogram, I need to get help with the software, and there is no Variogram in the pygslib library?


    On Thursday, July 4, 2019, 10:05:19 AM GMT+4:30, Nicholas Shea <notifications@github.com> wrote:  
 
 
Archived directory is attached, let me know if you are able to download and open it

Babbitt.zip

**Comment by nshea3** [comment]
Sorry, I misunderstood you! My mistake.
I cannot find the domain.stl file either unfortunately.

I do not think that pygslib implements variograms yet, I know you can use scikit-gstat, pygeostat, or geostatspy to get the variogram parameters.

**Comment by variog** [comment]
Please, no matter. Thank you for sending me domain.stl, otherwise I will not be able to run demo file.

    On Thursday, July 4, 2019, 11:34:16 PM GMT+4:30, Nicholas Shea <notifications@github.com> wrote:  
 
 
Sorry, I misunderstood you! My mistake.
I cannot find the domain.stl file either unfortunately.

I do not think that pygslib implements variograms yet, I know you can use scikit-gstat, pygeostat, or geostatspy to get the variogram parameters.

**Comment by opengeostat** [comment]
Hi all, 

The tutorial link https://opengeostat.github.io/pygslib/Tutorial_files/Tutorial_1.tar was restored and duplicated files removed from pygslib/pygslib/Ipython_templates/Tutorial_1.

Please note that the tutorial was updated to make it work with the development version (0.0.0.4.0.0 on Latest commit da9114e)
