### ISSUE TITLE
simple examples for kriging and sequential simulation

### ISSUE THREAD

**Issue by amirdel** [opengeostat/pygslib#4]
Hi, I just found your package and it looks very interesting. I was trying to wrap gslib for my research and I came across your work. Do you have any examples of calling gslib functions like kriging and sequential simulation?

**Comment by opengeostat** [comment]
amirdel, 

You will find a tutorial for Kriging at https://opengeostat.github.io/pygslib/Tutorial.html. You will find more detail at https://opengeostat.github.io/pygslib/API.html.

There is not simulation implemented yet.
