### ISSUE TITLE
FORTRAN kt3d code

### ISSUE THREAD

**Issue by markjuvert** [opengeostat/pygslib#40]
Good day everyone and thanks to the authors for creating such a great program. 

I'm trying to use this program in my study data but i can't replicate the demo lesson.  I have installed all the necessary libraries as described in the tutorial. The error occurs during estimation. 

# estimating in one block
estimate, debug, summary = pygslib.gslib.kt3d(kt3d_Parameters)

The error message i get is as follows:

Traceback (most recent call last):

  File "/Users/markjuvert/opt/anaconda3/lib/python3.6/site-packages/pygslib/gslib/__init__.py", line 1328, in kt3d
    output['outwmean']) =__gslib__kt3d.pykt3d(**parameters)

TypeError: 'bhidint' is an invalid keyword argument for this function

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/markjuvert/Desktop/Babbitt/Babbit.py", line 356, in <module>
    estimate, debug, summary = pygslib.gslib.kt3d(kt3d_Parameters)

  File "/Users/markjuvert/opt/anaconda3/lib/python3.6/site-packages/pygslib/gslib/__init__.py", line 1332, in kt3d
    raise NameError('unexpected error in FORTRAN kt3d code')
NameError: unexpected error in FORTRAN kt3d code
![Snip20200328_1](https://user-images.githubusercontent.com/60376215/77784842-2b2d0f00-7096-11ea-9478-55717ac35d70.png)

I've tried to trouble shoot the code in the best way i can but i'm stuck here. 

Please if anyone can help, I'll be very grateful.

Thanks in advanced!

**Comment by opengeostat** [comment]
What version of PyGSLIB are you using? The last version (0.0.0.6) will require  'bhidint'  in the parameter dictionary. Older versions will use  'bhid'. The keyword changed. Please make sure you are using the right keyword in your code and the last pygslib version. 
https://github.com/opengeostat/pygslib/blob/bc421f96bc46381d0ae2a6630acae5d760c2884d/pygslib/gslib/__init__.py#L1287

**Comment by opengeostat** [comment]
@markjuvert, I see what you mean now, and thank you for reporting this bug. There was a bug in the parameter dict of kt3d of the demo located in the wiki of pygslib. It is fixed now. Please download the last pygslib version 0.0.0.6 (conda package only available for python 3.8) and the demo located at https://github.com/opengeostat/pygslib/wiki/Demos/Demo1.7z and try again. 
You can get the last version with `conda install pygslib -c opengeostat -c conda-forge`
