### ISSUE TITLE
Python 3.8 support for Linux

### ISSUE THREAD

**Issue by euandekock** [opengeostat/pygslib#49]
Please can you run a build of the wheel for the Linux/Python 3.8 0.0.0.5.0.0 version. Most modern Linuxes now use 3.8 by default.

I see there is a 3.8 build for Windows.

I did try to build it locally under Fedora 32, but I'm getting all sorts of esoteric Fortran compiler errors.

Many Thanks,

**Comment by opengeostat** [comment]
Pygslib 0.0.0.6 is now available for Linux, Windows and Mac.
