### ISSUE TITLE
numpy dependency

### ISSUE THREAD

**Issue by amirdel** [opengeostat/pygslib#5]
I just installed the package using conda install. It worked, however it asked me to downgrade numpy:
numpy:        1.12.0-py27_0   --> 1.11.3-py27_0 
I was wondering if this is necessary or it can also be used along with python 1.12.

**Comment by basilrabi** [comment]
I installed it from souce (in fedora 28) and was able to use along with numpy 1.14

**Comment by opengeostat** [comment]
Hi amirdel, 

You may want to move to the development version of pygslib (git clone and then python setup.py develop). The conda distribution is a bit old now... 
We are planning to update these conda distributions but first we need to fix some issues and some changes in the code.
