### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Nicolasbustos** [opengeostat/pygslib#50]
I can't import de module in python 3.8

This is the output

ImportError                               Traceback (most recent call last)
<ipython-input-3-fc3bf9d8b71e> in <module>
----> 1 import pygslib

~\pygslib\pygslib\__init__.py in <module>
     24 
     25 # import pygslib modules (compatible with python 3x)
---> 26 from pygslib import drillhole, blockmodel, vtktools, nonlinear, sandbox, gslib, plothtml, charttable, progress, surpac
     27 
     28 from pygslib import version

~\pygslib\pygslib\gslib\__init__.py in <module>
     40 
     41 #gslib fortran code
---> 42 from pygslib.gslib import __gslib__kt3d
     43 from pygslib.gslib import __gslib__postik
     44 from pygslib.gslib import __read_gslib

ImportError: cannot import name '__gslib__kt3d' from partially initialized module 'pygslib.gslib' (most likely due to a circular import) (C:\Users\*********\pygslib\pygslib\gslib\__init__.py)

**Comment by opengeostat** [comment]
Try the Pygslib [win-64/pygslib-0.0.0.7.0.0-py39hb572761_0.tar.bz2](https://anaconda.org/opengeostat/pygslib/0.0.0.7.0.0/download/win-64/pygslib-0.0.0.7.0.0-py39hb572761_0.tar.bz2). This built is getting old now, you may also whant to build from source code.
