### ISSUE TITLE
Drillhole.merge has bugs

### ISSUE THREAD

**Issue by opengeostat** [opengeostat/pygslib#54]
Drillhole.merge function has bugs, not always work OK.

**Comment by opengeostat** [comment]
Drillhole.merge is now deprecated, use Drillhole.merge_table

**Comment by 10041964** [comment]
i am beginner learning with your tutorials, and downloaded all pygslib, but when running tutorial , got this message . can you assist.

AttributeError                            Traceback (most recent call last)
<ipython-input-34-7341d23081e8> in <module>
      1 # create drillhole object
----> 2 mydholes = pygslib.drillhole.Drillhole(collar, survey)
      3 
      4 # add intervall table
      5 mydholes.addtable(table = assay, table_name = 'assay')

AttributeError: module 'pygslib' has no attribute 'drillhole'

**Comment by AMERTERER** [comment]
how to create domain (domain.stl)
