### ISSUE TITLE
estimation domain generation

### ISSUE THREAD

**Issue by Maina-T** [opengeostat/pygslib#56]
I really need your help on how to generate estimation domain file

**Comment by opengeostat** [comment]
Hello @Maina-T 
Pygslib is not designed to create estimation domains. There is a level of minimum functionality to create 2D surfaces (`delaunay2D`, `delaunay2D_polylines`, and `rbfinterpolate` at `pygslib.vtktools`). There is also some intent to build functions for "implicit modelling" (`calculate_normals`, `implicit_surface`, `evaluate_implicit_points`, `define_region_grid`, `evaluate_region`, `set_region_field`, `extract_surface`, `evaluate_implicit_grid`, `clip_with_surface`). However, these are hard to use and do not perform well. I recommend you to have a look at [GemPy] (https://www.gempy.org/). It is a well-documented software and uses a robust technique to define domains.
