### ISSUE TITLE
Syntax error issues when using class Pandas Data Frame

### ISSUE THREAD

**Issue by nikki552** [opengeostat/pygslib#58]
Hello, 

I'm new to pygslib and I'm trying run the following when I get a syntax error. 

Can someone please help.

Thank you, 

>>> # import third party python libraries
>>> import pandas as pd
>>> import matplotlib.pylab as plt
>>> import numpy as np
>>> # make plots inline in Ipython Notebooks/QT terminal
>>> # %matplotlib inline

>>> # import pygslib
>>> import pygslib

>>> # importing data from file
>>> collar = pd.read_csv('collar_BABBITT.csv')
>>> survey = pd.read_csv('survey_BABBITT.csv')
>>> assay = pd.read_csv('assay_BABBITT.csv')

>>> print (type(collar))
<class 'pandas.core.frame.DataFrame'>

  Input In [7]
    <class 'pandas.core.frame.DataFrame'>
    ^
SyntaxError: invalid syntax

**Comment by opengeostat** [comment]
Hello @nikki552, 
This is a Pandas error.
