### ISSUE TITLE
No module named 'pygslib.drillhole' on 'import pygslib'

### ISSUE THREAD

**Issue by leonfoks** [opengeostat/pygslib#6]
I followed the install from source directions. The installation finishes with no errors or warnings.

Did I miss something?

opengeostats and pygslib are not found when using conda install -c opengeostats pygslib.

Thanks

**Comment by opengeostat** [comment]
Hi leonfoks, 

I am closing this issue becasue we will be moving to a new conda distribution based on wheels. This will allows installation of compiled code with pip.
