### ISSUE TITLE
Error when using pygslib on MacOS

### ISSUE THREAD

**Issue by exepulveda** [opengeostat/pygslib#9]
Hello,

After installing pygslib in Acancoda, which was successful, I tried to load the pygslib module:

import pygslib

I get the following error:
Unable to revert mtime: /Library/Fonts
Traceback (most recent call last):
  File "drillholes_comp.py", line 5, in <module>
    import pygslib
  File "/Users/esepulveda/anaconda3/envs/crcore/lib/python2.7/site-packages/pygslib/__init__.py", line 32, in <module>
    import gslib 
  File "/Users/esepulveda/anaconda3/envs/crcore/lib/python2.7/site-packages/pygslib/gslib/__init__.py", line 42, in <module>
    import __gslib__kt3d
ImportError: dlopen(/Users/esepulveda/anaconda3/envs/crcore/lib/python2.7/site-packages/pygslib/gslib/__gslib__kt3d.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/esepulveda/anaconda3/envs/crcore/lib/python2.7/site-packages/pygslib/gslib/__gslib__kt3d.so
  Reason: image not found

Apparently, there is a hardcoded reference to libgfortran. I installed libgfortran with conda, but the error is the same.

I hope you can find a solution. In the meantime, I will try to build it from sources.

**Comment by banesullivan** [comment]
+1 Is there any way to resolve this?

**Comment by opengeostat** [comment]
I'll try next week, my mac is at home...

**Comment by emreekm** [comment]
solution ??

**Comment by tunanottechnical** [comment]
Having the same issue on mac;

ImportError: dlopen(/Users/jackmaughan/anaconda3/lib/python3.6/site-packages/pygslib/gslib/__gslib__kt3d.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/jackmaughan/anaconda3/lib/python3.6/site-packages/pygslib/gslib/__gslib__kt3d.cpython-36m-darwin.so
  Reason: image not found

**Comment by raonisalomao** [comment]
Having the same issue..=(

===========================================================

ImportError                               Traceback (most recent call last)
<ipython-input-1-fc3bf9d8b71e> in <module>
----> 1 import pygslib

~/anaconda3/envs/py36GSLIB/lib/python3.6/site-packages/pygslib/__init__.py in <module>
     24 
     25 # import pygslib modules (compatible with python 3x)
---> 26 from . import drillhole, blockmodel, vtktools, nonlinear, sandbox, gslib, plothtml, charttable, progress
     27 
     28 from . import version

~/anaconda3/envs/py36GSLIB/lib/python3.6/site-packages/pygslib/gslib/__init__.py in <module>
     40 
     41 #gslib fortran code
---> 42 from . import __gslib__kt3d
     43 from . import __gslib__postik
     44 from . import __read_gslib

ImportError: dlopen(/Users/raonimacbookpro2016/anaconda3/envs/py36GSLIB/lib/python3.6/site-packages/pygslib/gslib/__gslib__kt3d.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/raonimacbookpro2016/anaconda3/envs/py36GSLIB/lib/python3.6/site-packages/pygslib/gslib/__gslib__kt3d.cpython-36m-darwin.so
  Reason: image not found

====================================================================

**Comment by KaplanEmrah** [comment]
Having the same issue on Mac, any solution after 2 years?

**Comment by graysuit** [comment]
having same issue, tried with latest on windows:
```bash
C:\Users\gray\source\repos\VTK_viewer\VTK_viewer\bin\x86\Debug>temp.py
Traceback (most recent call last):
  File "C:\Users\gray\source\repos\VTK_viewer\VTK_viewer\bin\x86\Debug\temp.py", line 4, in <module>
    import pygslib
  File "C:\Users\gray\miniconda2\lib\site-packages\pygslib\__init__.py", line 26, in <module>
    from pygslib import drillhole, blockmodel, vtktools, nonlinear, sandbox, gslib, plothtml, charttable, progress, surpac
  File "C:\Users\gray\miniconda2\lib\site-packages\pygslib\gslib\__init__.py", line 42, in <module>
    from pygslib.gslib import __gslib__kt3d
ImportError: DLL load failed while importing __gslib__kt3d: The specified module could not be found.
```
